### ISSUE TITLE
Unexpected `ORDER` rule violation

### ISSUE THREAD

**Issue by PaulSonOfLars** [yoheimuta/protolint#114]
[Certain protos](https://github.com/golang/protobuf/blob/e91709a02e0e8ff8b86b7aa913fdc9ae9498e825/protoc-gen-go/testdata/imports/test_import_a1m2.proto) contain simple `option` assignments at the top of the file, before the imports. Linting these results in the following lint violation:
`The order of Import is invalid. Check if the file is ordered in the correct manner.`

These are usually used for language-specific generated code ([java](https://developers.google.com/protocol-buffers/docs/reference/java-generated#invocation), [python](https://developers.google.com/protocol-buffers/docs/reference/python-generated#service), [go](https://developers.google.com/protocol-buffers/docs/reference/go-generated#package), [csharp](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#structure)), to help specify optional importpaths. 

My opinion is that there should be a toggle available to edit the `ORDER` setting, which allows simple `option` assignments to be placed before imports. This could be done in the following ways:
 - Through a global setting, where all simple top-level `option` assignments are placed before the import when using the `--fix` mode.
 - Through a whitelist system, where users can specify the specific `option` names to be placed at the top of the file.

**Comment by yoheimuta** [comment]
@PaulSonOfLars Thank you for taking care of the issue!

Let me know the following to understand the problem clearly.

> Certain protos contain simple option assignments at the top of the file, before the imports. Linting these results in the following lint violation:

These files are violating the file structure of the Google Style Guide. 
Is it right?

- ref. https://developers.google.com/protocol-buffers/docs/style#file-structure

> My opinion is that there should be a toggle available to edit the ORDER setting, which allows simple option assignments to be placed before imports.

You mean that the `ORDER` rule, which equals to the Google Style Guide, should allow a few exceptions about option and import in some situations, rather than forcing end-users to turn entire off. 
Is my understanding correct?

**Comment by PaulSonOfLars** [comment]
Seems like I missed the [structure style](https://developers.google.com/protocol-buffers/docs/style#file-structure) section; If thats what google recommends, then I would use that.

In which case, I'm just disappointed that they [ignore their own guidelines](https://github.com/golang/protobuf/blob/e91709a02e0e8ff8b86b7aa913fdc9ae9498e825/protoc-gen-go/testdata/imports/test_import_a1m2.proto)...

>You mean that the ORDER rule, which equals to the Google Style Guide, should allow a few exceptions about option and import in some situations, rather than forcing end-users to turn entire off.

Yes, that was what I was saying. However, if the styleguide says file options should be after imports, then I might be wrong, and your approach might be better.
