### ISSUE TITLE
Parsing breaks on empty fields within options within RPCs

### ISSUE THREAD

**Issue by torkelrogstad** [yoheimuta/protolint#123]
Parsing breaks when including an option with an empty message within the option. The below snippet compiles fine in `protoc`, but doesn't parse with protolint.

```proto
syntax = "proto3";

service Foo {
  rpc Bar(Baz) returns (Baz) {
    option (opt) = {
      empty : {}
    };
  }
}

message Baz {}
```

**Comment by yoheimuta** [comment]
@torkelrogstad Thank you for reporting this issue! I'll check it out.

**Comment by yoheimuta** [comment]
@torkelrogstad I fixed it.
Please confirm if it works well whenever you have time.

- ref. https://github.com/yoheimuta/protolint/releases/tag/v0.23.2

**Comment by torkelrogstad** [comment]
Can confirm it works for me. Thank you for making a great tool!
