### ISSUE TITLE
swagger annotations break the protolinter

### ISSUE THREAD

**Issue by KowsikaRamachandran** [yoheimuta/protolint#128]
I have tried to run protolinter on the proto files with swagger annotations, but itseems to break the linter with below error:

found "\"max_length\"(Token=2, Pos=..\\protos\\test.proto:179:5)" but expected [}] at C:/Users/uname/go/src/github.com/yoheimuta/go-protoparser/parser/field.go:243:found "ma
x_length" but expected  at C:/Users/uname/go/src/github.com/yoheimuta/go-protoparser/internal/lexer/emptyStatement.go:16

Below is a sample proto message with annotations:

message UserCredentials {
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_schema) = {
		example: { value: '{ "email_id": "user@domain.com", "password": "password@123"}' }
    };
    string email_id = 1[(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
    pattern: "^[-!#$%&'*+\\/0-9=?A-Z^_a-z{|}~](\\.?[-!#$%&'*+\\/0-9=?A-Z^_a-z`{|}~])*@[a-zA-Z0-9](-*\\.?[a-zA-Z0-9])*\\.[a-zA-Z](-?[a-zA-Z0-9])+$"
    max_length: 254
    min_length: 1
    description: "Enter user email"
	}];
    string password = 2[(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
    description: "Enter user password"
	}];
}

**Comment by yoheimuta** [comment]
@KowsikaRamachandran Thank you for reaching out!
I'm going to investigate it.

**Comment by KowsikaRamachandran** [comment]
Thank you for the response. Kindly investigate this issue using the below proto:
https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto

**Comment by yoheimuta** [comment]
@KowsikaRamachandran I fixed it. 
Please confirm https://github.com/yoheimuta/protolint/releases/tag/v0.25.1 and close it if it works fine.

**Comment by KowsikaRamachandran** [comment]
Thanks! @yoheimuta, Linter works on swagger annotated protos.
