### ISSUE TITLE
Feature: enum prefix

### ISSUE THREAD

**Issue by Antonboom** [yoheimuta/protolint#152]
https://developers.google.com/protocol-buffers/docs/style#enums

```protobuf
enum FooBar {
  FOO_BAR_UNSPECIFIED = 0;
  FOO_BAR_FIRST_VALUE = 1;
  FOO_BAR_SECOND_VALUE = 2;
}
```

Prefer prefixing enum values instead of surrounding them in an enclosing message.

**Comment by yoheimuta** [comment]
@Antonboom Thank you for your feature request.
When I have time, I'm getting to it if anybody still doesn't work on it.

**Comment by yoheimuta** [comment]
@Antonboom I added a new rule ENUM_FIELD_NAMES_PREFIX that is enabled by default.
It would be nice if you check it works for you.

- ref. 
  - https://github.com/yoheimuta/protolint/releases/tag/v0.31.0
  - https://github.com/yoheimuta/protolint#rules

**Comment by Antonboom** [comment]
@yoheimuta, thanks!

I'm trying to understand google developers and it seems that this rule only applies to enums outside of posts.
What do you think?

```
prefixing ... instead of surrounding ... 
```

**Comment by yoheimuta** [comment]
@Antonboom As you said, it seems ambiguous.

However, I'm sure that people came up with this rule to avoid tricky name collisions on C++. 
Then, it rules out wrapping by a message.

```proto
message MyEnumMessage {
  enum MyEnum {
   A = 0;
   B = 1;
  }
}

message MyOtherEnumMessage {
  enum MyOtherEnum {
   A = 0;
   B = 1;
  }
}
```

- ref. https://github.com/protocolbuffers/protobuf/issues/8230#issue-792859078

The name collisions can occur even between enums wrapped by a message.

```proto
syntax = "proto3";
package example;

message Wrap {
  enum FooBar {
    FOO_BAR_UNSPECIFIED = 0;
    FOO_BAR_FIRST_VALUE = 1;
    FOO_BAR_SECOND_VALUE = 2;
  }

  enum BarBaz {
    BAR_BAZ_UNSPECIFIED = 0;
    BAR_BAZ_FIRST_VALUE = 1;
    BAR_BAZ_SECOND_VALUE = 2;
  }

  FooBar fb = 1;
  BarBaz bb = 2;
}

message Wrap2 {
  enum FooBar {
    UNSPECIFIED = 0;
    FIRST_VALUE = 1;
    SECOND_VALUE = 2;
  }

  enum BarBaz {
    UNSPECIFIED = 0;
    FIRST_VALUE = 1;
    SECOND_VALUE = 2;
  }

  FooBar fb = 1;
  BarBaz bb = 2;
}

```

```
❯❯❯ protoc --proto_path=./_example/proto --go_out=./ ./_example/proto/dup_enum.proto
dup_enum.proto:29:5: "UNSPECIFIED" is already defined in "example.Wrap2".
dup_enum.proto:29:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "UNSPECIFIED" must be unique within "example.Wrap2", not just within "BarBaz".
dup_enum.proto:30:5: "FIRST_VALUE" is already defined in "example.Wrap2".
dup_enum.proto:30:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "FIRST_VALUE" must be unique within "example.Wrap2", not just within "BarBaz".
dup_enum.proto:31:5: "SECOND_VALUE" is already defined in "example.Wrap2".
dup_enum.proto:31:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "SECOND_VALUE" must be unique within "example.Wrap2", not just within "BarBaz".
```

All things considered, the reasoning that a rule should only apply to top-level enums sounds weak to me.

**Comment by Antonboom** [comment]
I see. Thanks!

**Comment by yrtimiD** [comment]
Would it be acceptable/useful to enhance this feature with the setting to allow shorter acronym prefix?
```
enum FooBar {
  FB_UNSPECIFIED = 0;
  FB_FIRST_VALUE = 1;
  FB_SECOND_VALUE = 2;
}
```

**Comment by hellt** [comment]
@yoheimuta Why do google itself follow this rule only for first enum value?


https://github.com/googleapis/googleapis/blob/4d27ae79c480f0de8e88aae02c53ee7fb9fc03f5/google/cloud/retail/v2/model.proto#L54

https://github.com/googleapis/googleapis/blob/4d27ae79c480f0de8e88aae02c53ee7fb9fc03f5/google/type/dayofweek.proto#L26
