### ISSUE TITLE
Support for Google API Linter

### ISSUE THREAD

**Issue by jankrynauw** [yoheimuta/protolint#154]
Hi

Is there a way to support the Google API Linter - https://linter.aip.dev/

**Comment by yoheimuta** [comment]
@jankrynauw I'm afraid the answer is NO at the moment.
If you have any ideas, please let me know.

**Comment by jankrynauw** [comment]
We just created our own plugin for this: https://plugins.jetbrains.com/plugin/16164-aip-linter which have a link to the source code for some ideas.
