### ISSUE TITLE
Configurable naming conventions

### ISSUE THREAD

**Issue by agasparovic** [yoheimuta/protolint#160]
Hi @yoheimuta, thanks so much for creating protolint!

My company's internal proto style guidelines are similar to Google's, but have a couple of naming differences. Notably, we use lowerCamelCase for RPC names instead of UpperCamelCase.

What do you think about making rules for checking that names conform to a configurable convention, rather than a hardcoded one?

For instance, an RPC_NAMING rule could default to "upper_camel_case" (per the Google guidelines), but allow configuring: 
* upper_camel_case
* lower_camel_case
* upper_snake_case
* lower_snake_case

**Comment by yoheimuta** [comment]
@agasparovic Thank you for reaching out!
Having an option to configure case conventions sounds good 👍

**Comment by yoheimuta** [comment]
@agasparovic Hi, I created PR #170.
Since this is slightly different from what you suggested, let me know what you think if you have time.

**Comment by agasparovic** [comment]
@yoheimuta - Wow that looks perfect for our use case! Thanks so much for adding.

**Comment by yoheimuta** [comment]
I've cut a release v0.33.0 https://github.com/yoheimuta/protolint/releases/tag/v0.33.0.
And I'm closing this issue for now. 

PS. If somebody **really** wants the other `something_NAME_CASE` rules, I think it's worth reopening or creating a new one.
