### ISSUE TITLE
Attempt to find configuration file in current and parent folders

### ISSUE THREAD

**Issue by jpreese** [yoheimuta/protolint#164]
At the moment to specify a configuration directory one needs to specify `config_path` or `config_dir_path`. It would be nice to not have to specify these in the case that the configuration is just a single (potential a few more) directories up.

In other words if I have:

```
parent/
  .protolint.yaml
  child/
    foo.proto
```

and I run `protolint lint parent/child/foo.proto` , protolint could check the current directory, and the directory above, and the directory above, etc.

**Comment by yoheimuta** [comment]
Thank you for reaching out!
Sounds nice.

**Comment by yoheimuta** [comment]
@jpreese I've supported the feature (ref also. https://github.com/plexsystems/vscode-protolint/issues/19) and published [v0.32.0](https://github.com/yoheimuta/protolint/releases/tag/v0.32.0).
Can you confirm it works?
