### ISSUE TITLE
Using docker image in CI

### ISSUE THREAD

**Issue by reitzmichnicht** [yoheimuta/protolint#177]
With the change from alpine to scratch the docker image is now not longer usable inside jenkins:

22:27:54  java.io.IOException: Failed to run image 'yoheimuta/protolint'. Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"cat\": executable file not found in $PATH": unknown.
22:27:54  	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:145)

          agent {
            docker {
              image "yoheimuta/protolint"
              registryUrl "https://index.docker.io/v1/"
              alwaysPull true
              reuseNode true
              args '-i --entrypoint='
            }
          }

Jenkins can not use the entrypoint, instead it executes shell commands inside the docker container. And for whatever dirty reason it executes hard coded a cat command to see if the container is responsive.

**Comment by yoheimuta** [comment]
@reitzmichnicht Thank you for reporting the issue!
I'm reverting the base image from scratch to alpine soon.

**Comment by yoheimuta** [comment]
```
# before the change
(base) ~/w/p/g/s/g/y/protolint ❯❯❯ docker run --entrypoint "which" yoheimuta/protolint:v0.32.0 cat
/bin/cat

# latest
(base) ~/w/p/g/s/g/y/protolint ❯❯❯ docker run --entrypoint "which" yoheimuta/protolint:v0.35.0 cat
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "which": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 

# new
(base) ~/w/p/g/s/g/y/protolint ❯❯❯ docker run --entrypoint "which" yoheimuta/protolint:v0.35.1 cat
Unable to find image 'yoheimuta/protolint:v0.35.1' locally
v0.35.1: Pulling from yoheimuta/protolint
e519532ddf75: Already exists 
5012c2f2111e: Pull complete 
Digest: sha256:d8e93014b6761c8a25e01426565e9080aa148f83e6524b4da7b0975e0199d08b
Status: Downloaded newer image for yoheimuta/protolint:v0.35.1
/bin/cat
```

**Comment by yoheimuta** [comment]
@reitzmichnicht I fixed it.
Can you give it a try using the latest (v0.35.1)?

**Comment by reitzmichnicht** [comment]
thank you very much, it's working again without issues
