### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by jack24254029** [yoheimuta/protolint#179]
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the yoheimuta/protolint tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/yoheimuta/homebrew-protolint/Formula/protolint.rb:9
```

**Comment by justinfarrelldev** [comment]
Same issue here, also with brew. 
Ran into it trying to do `brew upgrade go` from go 1.15.7 to latest.

**Comment by yoheimuta** [comment]
Thank you for reporting!

It may be fixed by releasing a new formula as the dependent latest go-releaser fixes this issue.
I'll give it a try.

- ref.
  - https://github.com/goreleaser/goreleaser/pull/2591
  - https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0

**Comment by yoheimuta** [comment]
@jack24254029 I fixed it by updating. Can you confirm the latest version?
The line is removed: https://github.com/yoheimuta/homebrew-protolint/commit/8530af409ef7d4ece5166337d65661980218c026#diff-2b45ff9d66679da6d26162df33a655de4997f510f54431c1920504d65b24f0c3

**Comment by jack24254029** [comment]
> @jack24254029 I fixed it by updating. Can you confirm the latest version? The line is removed: [yoheimuta/homebrew-protolint@8530af4#diff-2b45ff9d66679da6d26162df33a655de4997f510f54431c1920504d65b24f0c3](https://github.com/yoheimuta/homebrew-protolint/commit/8530af409ef7d4ece5166337d65661980218c026#diff-2b45ff9d66679da6d26162df33a655de4997f510f54431c1920504d65b24f0c3)

Yes, it is fixed.
Thank you.
