### ISSUE TITLE
please support proto3 optional for code generator

### ISSUE THREAD

**Issue by qinyuguang** [yoheimuta/protolint#234]
protoc version: v3.18.1
protoc-gen-protolint version: v0.37.1

### test.proto
```protobuf
syntax = "proto3";

package test;

message Test {
  optional string foo = 1;
}
```

### command
```bash
protoc --protolint_out=. test.proto
```

### output
test.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-protolint hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--protolint_out:

**Comment by yoheimuta** [comment]
Thank you for reaching out!
I'm swamped with the upcoming conference now, but I'll get back to this issue next weekends.

**Comment by yoheimuta** [comment]
@qinyuguang I fixed it!
Can you confirm v0.38.0?

- https://github.com/yoheimuta/protolint/releases/tag/v0.38.0
