### ISSUE TITLE
Notice: vscode-protobuflint

### ISSUE THREAD

**Issue by jpreese** [yoheimuta/protolint#25]
Again, thanks for putting this project together.

As I mentioned in PR #24, the next logical step would be to get this into Visual Studio Code so that users can lint their `.proto` files as they type.

I put together a MVP here (https://github.com/jpreese/vscode-protobuflint). It uses your tool on the backend, and renders any linting errors to the editor.

I haven't cut a release to the marketplace yet, but just wanted to let you know it's in the works.

**Comment by yoheimuta** [comment]
That's impressive!
Thank you for sharing your work.

**Comment by jpreese** [comment]
No problem! Feel free to close this if you want. Just wanted to make you aware that the repository now exists.

I've got it in a state now that should make it MVP. You can grab a release from the releases page (https://github.com/jpreese/vscode-protobuflint/releases).

After its been battle-tested some, I'll push it to the marketplace.

**Comment by yoheimuta** [comment]
I see. I'm looking forward to the release.
And I added it to users. Thanks.

- ref. https://github.com/yoheimuta/protolint#users

**Comment by yoheimuta** [comment]
(@jpreese )

I have cut a release for `intellij-protolint` under the influence of `vscode-protolint`.
The example section in the README is based on `vscode-protolint` because it looks good. 

Thank you!

- https://github.com/yoheimuta/protolint/pull/33
- https://plugins.jetbrains.com/plugin/12641-protocol-buffer-linter

**Comment by jpreese** [comment]
@yoheimuta you're welcome! Good idea to expand it to other editors.
