### ISSUE TITLE
Feature request: alternate to -fix there should be a -comment-out arg

### ISSUE THREAD

**Issue by acgreek** [yoheimuta/protolint#269]
we have a massive repo of protobuf definitions and others are objecting to breaking the existing apis that result from using '-fix', so as an alternative, it would be nice if there was '-comment-out' that would add the ```//protolint:disable:this .. ``` through out the code instead of fixing the problems. We could enable all linters and run with this arg once on our existing code base, and then all new code would have to meet all the linter requirements going forward (not allowing any new exceptions via code review)

**Comment by yoheimuta** [comment]
Thank you! Your feature request makes sense 👍

**Comment by yoheimuta** [comment]
@acgreek I just implemented a new flag `--auto_disable.`
I'm going to support the rest of the rules.
Whenever you have time, much appreciated if you let me know any feedback.

**Comment by yoheimuta** [comment]
@acgreek I've cut a release at https://github.com/yoheimuta/protolint/releases/tag/v0.40.0.
Can you give it a try?

**Comment by yoheimuta** [comment]
You should use `-fix -auto_disable=this` instead of `-fix.`

**Comment by acgreek** [comment]
works. Thank you

**Comment by yoheimuta** [comment]
Good to hear that!
