### ISSUE TITLE
pluralised check should (IMHO) be case insensitive

### ISSUE THREAD

**Issue by quintilation** [yoheimuta/protolint#294]
We have field names which end in an ID, we pluralise these with a lower case 's' which I feel is reasonable. protolint disagrees and complains:

` Repeated field name "RunningOnDeviceIDs" must be pluralized name "RunningOnDeviceIDS"`

I am not sure if this is by design or a bug, but I thought I would report it anyway.

**Comment by yoheimuta** [comment]
Thank you for reporting to me!
You have a point. I'm getting to it.

**Comment by yoheimuta** [comment]
@quintilation I fixed it.
Can you give it a try [v0.42.2](https://github.com/yoheimuta/protolint/releases/tag/v0.42.2) when you have time?

**Comment by yoheimuta** [comment]
I fixed it and some time passed, so I'm closing this issue.
