### ISSUE TITLE
Suggestion: Windows Release

### ISSUE THREAD

**Issue by jpreese** [yoheimuta/protolint#30]
I think it would be beneficial to also generate a Windows binary when creating releases

**Comment by yoheimuta** [comment]
@jpreese Thank you for your suggestion!
I'm all for it. I will do it.

**Comment by yoheimuta** [comment]
From v0.9.4 onwards, a release includes Windows binaries.

- ref. https://github.com/yoheimuta/protolint/releases/tag/v0.9.4
