### ISSUE TITLE
plural of uri is handled wrongly

### ISSUE THREAD

**Issue by paradoxon82** [yoheimuta/protolint#312]
Hello,

we have *.proto files that contain members like this:
`repeated string module_uri = 3;`
after the first run, using the -fix flag, we get:
`repeated string module_uris = 3;`
but this still fails the pluralization check, if we use -fix again, we get
`repeated string module_urises = 3;`

This seems not really correct. 
Can you please check?

Best Regards,
Daniel

**Comment by yoheimuta** [comment]
Hi, sorry for the late reply!
You're right. This does not seem correct.

I'll look into it this weekend. Thank you very much!

**Comment by yoheimuta** [comment]
@paradoxon82 I fixed this issue by [v0.43.1](https://github.com/yoheimuta/protolint/releases/tag/v0.43.1).
Can you give it a try when you have a moment?

**Comment by yoheimuta** [comment]
Good to hear that!
