### ISSUE TITLE
Publish protoc-gen-protolint to Maven Central

### ISSUE THREAD

**Issue by davidjlynn** [yoheimuta/protolint#328]
When using protoc in Gradle, it is possible to pull protoc plugins from maven central.

This feature was recently added to protoc-gen-doc, it would be good to get this plugin published as well.

I can open a PR to add the functionality.

**Comment by davidjlynn** [comment]
Thanks for merging @yoheimuta , looks like the release job worked. 🥳 
I cannot see the published artefact yet.
Perhaps it may take a little while to appear, however just wanted to mention there is some manual steps required every time a release is made to publish the libraries.
I detailed these in contributing: https://github.com/yoheimuta/protolint/blob/master/CONTRIBUTING.md#publish-the-maven-artifacts
Unfortunately I cannot check, but just thought I would let you know in case this was missed 😄 
Let me know if there was any extra issues.

**Comment by davidjlynn** [comment]
This is now complete, thank you for accepting the PRs, I will close the issue now.

**Comment by GVladi** [comment]
Is it really working now? The latest version of the plugin in maven central is 0.44.0.

**Comment by davidjlynn** [comment]
@GVladi yes, but there are manual steps needed on each release of a version.
Note the steps mentioned here https://github.com/pseudomuto/protoc-gen-doc/blob/master/CONTRIBUTING.md#publish-the-maven-artifacts
@yoheimuta could you release the newer versions?

**Comment by yoheimuta** [comment]
@GVladi @davidjlynn Thank you for letting me know!
I've released the new version: https://central.sonatype.com/artifact/io.github.yoheimuta/protoc-gen-protolint/versions

<img width="1439" alt="image" src="https://github.com/yoheimuta/protolint/assets/1223268/0dc78d94-4868-4916-9a0b-c0b53ce9805b">

**Comment by carstencodes** [comment]
@yoheimuta Are the manual steps ot be done on server side, i.e. maven central or is it on the github workflow side?

**Comment by davidjlynn** [comment]
@carstencodes the manual steps are all on maven central, detailed here: https://github.com/yoheimuta/protolint/blob/master/CONTRIBUTING.md#publish-the-maven-artifacts
Simply maven central needs to run checks and then the artifact be released.

**Comment by carstencodes** [comment]
@davidjlynn Ah, I see, so there is nothing to improve here. Sad to hear.
