### ISSUE TITLE
FILE_NAMES_LOWER_SNAKE_CASE: an issue with dot separated filenames

### ISSUE THREAD

**Issue by AlexCannonball** [yoheimuta/protolint#340]
Hello,

The linter suggests wrong fix for dot separated filenames. For example, a file `dot.separated.proto` receives the following error message:
`"File name \"dot.separated.proto\" should be lower_snake_case.proto like \"dot.separated.proto\"."`

As I understand, dot separated names doesn't follow the rule/guidelines, so it should suggest setting to `"dot_separated.proto"`.

Thank you.

**Comment by yoheimuta** [comment]
@AlexCannonball Thank you for creating this issue!
https://github.com/yoheimuta/protolint/releases/tag/v0.45.2 should fix it.

**Comment by AlexCannonball** [comment]
@yoheimuta Thank you, I confirm it's not reproducing after the fix.
