### ISSUE TITLE
Bug: Missing 'new' in https://github.com/yoheimuta/protolint/blob/master/bdist/js/install.mjs

### ISSUE THREAD

**Issue by pekarasa** [yoheimuta/protolint#426]
The keyword 'new' is missing in line 31 of the install.mjs file.
The line should look like this:
  agent = new HttpProxyAgent(process.env.PROTOLINT_PROXY);

It would be even better if process.env.HTTP_PROXY or process.env.HTTPS_PROXY were used for Windows instead.

**Comment by carstencodes** [comment]
I'll take a look at that. But I am very busy at the moment, might take until the end of the week.

**Comment by carstencodes** [comment]
Hi @pekarasa,

can you take a look at #427, if it goes into the right direction.

**Comment by pekarasa** [comment]
Hello carsencodes,
works fine, just downloaded and tested.
Thank you very much!

**Comment by yoheimuta** [comment]
I just published the release with this fix: https://github.com/yoheimuta/protolint/releases/tag/v0.50.4.
Thanks!
