### ISSUE TITLE
please fix license inconsistency

### ISSUE THREAD

**Issue by mohrr** [yoheimuta/protolint#429]
The [license file](https://github.com/yoheimuta/protolint/blob/master/LICENSE) for this repo says `Copyright (c) 2018 yohei yoshimuta`. However, the readme includes an [acknowledgement](https://github.com/yoheimuta/protolint/tree/master?tab=readme-ov-file#acknowledgement) that [prototool](https://github.com/uber/prototool) was "referred to...for...some source code". The [license file](https://github.com/uber/prototool/blob/dev/LICENSE) for prototool says `Copyright (c) 2019 Uber Technologies, Inc.`. That copyright is missing from this repository. This inconsistency makes it hard for my team to use this repository.

If this repository is no longer using code from prototool, please remove the acknowledgement (or at least the "source code" part of it). If it is still using code from prototool, please add the prototool copyright line to this repo's license file.

**Comment by yoheimuta** [comment]
@mohrr I just removed the acknowledgement part. Thank you for the headsup.
https://github.com/yoheimuta/protolint/blob/master/README.md#license
