### ISSUE TITLE
Feature request: junit output

### ISSUE THREAD

**Issue by tomascassidy** [yoheimuta/protolint#59]
It would be nice if protolint could output it's error messages in JUnit xml format.

This would make it easy to integrate with Jenkins and other CI tools for reporting linting errors.

**Comment by yoheimuta** [comment]
@tomascassidy Thank you for your request. Sounds good!
I have considered that it is arguably beneficial to support various formats. Therefore, I will implement the JUnit output in a bit.

**Comment by yoheimuta** [comment]
@tomascassidy I have cut a release to introduce a JUnit reporter. See #62 in detail.
You can grab the release from https://github.com/yoheimuta/protolint/releases/tag/v0.15.0.

If anything with wrong when you give it a try, please reopen this issue or open the new one and let me know.
