### ISSUE TITLE
Publish the linter to NPM

### ISSUE THREAD

**Issue by mrmeku** [yoheimuta/protolint#64]
People love linting! Lets let the Javascript projects join in on the fun too.

**Comment by mrmeku** [comment]
If you're open to the idea of publishing to NPM I can make a PR to help get everything together. I just want to gauge interest first

**Comment by jpreese** [comment]
What were you thinking in regards to npm? I feel like with an npm script command you could just run protolint,

**Comment by jpreese** [comment]
This is probably something we can close @yoheimuta, I don't think there's enough context here to really act on anything and the author seems to have disappeared.

**Comment by yoheimuta** [comment]
@mrmeku Thank you for the feature request. Please feel free to report an issue if there is anything.

@jpreese Thank you for taking care of the issue.
