### ISSUE TITLE
Command line argument for version info

### ISSUE THREAD

**Issue by wwuck** [yoheimuta/protolint#67]
It would be nice to have protolint output it's version string when outputting the help information.

Some possibilities:

`protolint` output could be amended to output version information.
`protolint -version` could output just the version information.
`protolint -help` could output the help/usage information and version information.

**Comment by yoheimuta** [comment]
@tomascassidy Thank you for your suggestion!

It makes sense.

> protolint -version could output just the version information.

This way seems to be an easier way for now.

**Comment by yoheimuta** [comment]
I added a new subcommand "version".

```
$ protolint version
protolint version 0.20.0(8bf4c69)
```
