### ISSUE TITLE
Output format not supported by CI tools

### ISSUE THREAD

**Issue by davidhart82** [yoheimuta/protolint#85]
Hi, excellent tool, we're considering using it as part of our CI environment.

The one issue at have is that the output format is not supported by any of the jenkins plugins we use (and junit isn't really the right format for a linter to output).

I'm considering adding protolint parsers to the plugins we use (warnings-ng and any that use violatons lib), if you think that's OK? Unless there is a more common standard linting format that this tool could use?

Thanks

**Comment by davidhart82** [comment]
I've added a PR for violations-lib: https://github.com/tomasbjerre/violations-lib/pull/79

**Comment by davidhart82** [comment]
And analysis model: https://github.com/jenkinsci/analysis-model/pull/236

**Comment by yoheimuta** [comment]
@davidhart82 Thank you for your feedback and suggestion!

> if you think that's OK?

Of course, it's OK. I appreciate your work. 
I'd like to add your contribution to the README blurb after your PRs will be merged.

> Unless there is a more common standard linting format that this tool could use?

You mean that protolint should have a more standard reporter, right? If you have any suggestions(such as JSON or some template style), please let me know. 

- ref. https://github.com/yoheimuta/protolint#reporters

**Comment by davidhart82** [comment]
https://github.com/jenkinsci/warnings-ng-plugin/pull/241

**Comment by davidhart82** [comment]
https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/warnings-ng-7.1.0

**Comment by yoheimuta** [comment]
> I'd like to add your contribution to the README blurb after your PRs will be merged.

I added a commit.

- ref. https://github.com/yoheimuta/protolint/commit/cdf1b6b9d4b26d21bae69cd9843b47b4ad740675
